### ISSUE TITLE
Moving windows make them disappear/blink

### ISSUE THREAD

**Issue by jaszhix** [linuxmint/muffin#398] opened 2018-12-16 17:21 UTC
Moved from linuxmint/Cinnamon#8052, @bitstrings wrote: 
#
```
 * Cinnamon version 4.0.2
 * Distribution - Manjaro
 * AMD 580 GPU (amdgpu)
 * 64 bit
 * kernel 4.19.2
 ```

Moving windows make them disappear.

Video (4K Screen) -> [HERE](https://drive.google.com/file/d/1G_WCjCnWB7JH8Ofo2Gj6CcB831jYUTEB/view?usp=sharing)

The is NO CLUTTER_* in environment.

In fact this is a fresh install without mod.

I've got a AMD 580 GPU using the free amdgpu.

Also, performance is iffy. Things are a bit jerky. Tried everything.

With or without xorg.conf.

xorg.conf
```
Section "Device"
	Identifier  "Card1"
	Driver      "amdgpu"
	VendorName  "AMD"
	BoardName   "Radeon RX 580"

    Option "TearFree" "on"
    Option "DRI" "3"
    Option "EnablePageFlip" "on"
EndSection
```

**Comment by rsi9x** [comment] 2019-01-17 10:32
I am having similar rendering issues after upgrading to Mint Cinnamon from 19 to 19.1.  In my case, the problem seems to affect only the second and third monitors.  It seems that the left-most monitor is unaffected (regardless if it's the primary monitor or not).  Whichever monitor I set as the left-most monitor is always unaffected.  On the center/right monitors, when drag a window to it, sometimes the window (or parts of the window) will flash or completely disappear.  Other times, the decoration remains, but the contents disappear (see video

[mint191_glitching_window_960.mp4.zip](https://github.com/linuxmint/muffin/files/2768218/mint191_glitching_window_960.mp4.zip)

).  
When I interact with the window, the contents usually reappear, but may disappear again if I drag it elsewhere. The desktop wallpaper on the affected monitors will sometimes also randomly flicker. The problem seems to go away as long as a window remains maximized on the affected monitors.

Things I've tried to no avail:
- Removing desktop background
- Changing display resolution
- Reducing number of monitors to 2
- Changing which monitor was primary 
- Both Open Source and Proprietary Nvidia drivers (390 ~ 415)
- Toggled "Enable VBlank" in General settings
- Enabled full composition pipeline in Nvidia settings
- Fresh install of Mint 19.1
- Restating Cinnamon (ALT+F2, r) - this does make the window reappear temporarily, but the problem reoccurs.

I installed MATE on the system, and was not able to reproduce the issue using MATE.

As previously mentioned, the issue affects both the proprietary Nvidia driver and Nouveau driver, and is reproducible when booting from the 19.1 ISO as well.

System information below:

<pre>
System:    Host: Mint191 Kernel: 4.18.0-13-generic x86_64 bits: 64 Desktop: Cinnamon 4.0.9 Distro: Linux Mint 19.1 Tessa 
Machine:   Type: Desktop System: Gigabyte product: X470 AORUS ULTRA GAMING v: N/A serial: <root required> 
           Mobo: Gigabyte model: X470 AORUS ULTRA GAMING-CF v: x.x serial: <root required> UEFI: American Megatrends v: F3 
           date: 08/08/2018 
CPU:       Topology: 8-Core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP L2 cache: 4096 KiB 
           Speed: 1893 MHz min/max: 2200/3700 MHz Core speeds (MHz): 1: 1887 2: 1991 3: 2078 4: 2129 5: 2125 6: 2125 7: 4175 
           8: 4251 9: 1892 10: 1891 11: 2198 12: 2080 13: 2007 14: 1896 15: 2126 16: 2126 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 415.27 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 1600x1200~60Hz, 1920x1200~60Hz, 1600x1200~60Hz 
           OpenGL: renderer: GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 415.27 
Audio:     Device-1: NVIDIA GP106 High Definition Audio driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k4.18.0-13-generic 
Network:   Device-1: Intel I211 Gigabit Network driver: igb 
           IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: xx:xx:xx:xx:xx:xx 
Drives:    Local Storage: total: 1.02 TiB used: 18.58 GiB (1.8%) 
           ID-1: /dev/sda vendor: Patriot model: Pyro size: 111.79 GiB 
           ID-2: /dev/sdf vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB 
Partition: ID-1: / size: 109.04 GiB used: 18.57 GiB (17.0%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 54.2 C mobo: N/A gpu: nvidia temp: 56 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 17% 
Info:      Processes: 308 Uptime: 37m Memory: 31.42 GiB used: 2.52 GiB (8.0%) Shell: bash inxi: 3.0.27 

</pre>

Thanks for all that you do. Mint 19.1 looks & works really great otherwise!

**Comment by jaszhix** [comment] 2019-01-17 10:46
Thanks. Can you try this version of muffin and see if it fixes it? It's muffin 4.0.6 with #405 applied.

[muffin-4.0.6-PR-405.tar.gz](https://github.com/linuxmint/muffin/files/2768269/muffin-4.0.6-PR-405.tar.gz)

**Comment by rsi9x** [comment] 2019-01-17 11:02
I installed gir1.2-meta-muffin-0.0, libmuffin0, muffin, muffin-common and muffin-dbg from the tar package, then logged out/back in, and the problem persists.

**Comment by jaszhix** [comment] 2019-01-17 11:08
OK, I suspect it's related to the actor flags set on the window group. Here's a build with it removed.

[muffin-4.0.6-405-window-group-no-flags-set.tar.gz](https://github.com/linuxmint/muffin/files/2768358/muffin-4.0.6-405-window-group-no-flags-set.tar.gz)

**Comment by rsi9x** [comment] 2019-01-17 17:52
Installing the packages from muffin-4.0.6-405-window-group-no-flags-set.tar.gz seems to have resolved the issue with the window contents flickering/disappearing.   I have not been able to reproduce the issue so far with my brief testing this morning.  I'll report back if something changes.

**Comment by jaszhix** [comment] 2019-01-17 23:32
Thanks for testing. I added the patch to #405.

**Comment by rsi9x** [comment] 2019-01-18 06:08
Thank you.  It seems like the issue with the glitching window contents is resolved by this patch.  However, I am noticing other glitches -- in some applications, it seems like a button is mistaken for a window, and a button shadow is incorrectly rendered in the top-left corner of the screen momentarily.  Sometimes an entire menu from the window is momentarily drawn in the top-left corner of the screen as well.   This happens most noticeably in the Steam app.  See video below:
[mint191_menu_glitch.mp4.zip](https://github.com/linuxmint/muffin/files/2771746/mint191_menu_glitch.mp4.zip)

**Comment by jaszhix** [comment] 2019-01-18 06:46
Is this a new issue since the patch I gave you? 

I decided to work-around the actor flag optimization some more because I think removing it introduces a performance regression. Instead it will be disabled during grab operations, which seems to be where it caused issues. I'm not reproducing the steam artifacts on my end, so maybe you could try this build?

[muffin-4.0.6-405-226e07df444bc289bff3e83da4acbf56679202ad.tar.gz](https://github.com/linuxmint/muffin/files/2771830/muffin-4.0.6-405-226e07df444bc289bff3e83da4acbf56679202ad.tar.gz)

**Comment by rsi9x** [comment] 2019-01-18 09:20
No, this is not a new issue introduced by the patch.   I tested it with the 4.0.6 release version, and it has the same issue.  I do not recall this occurring with Mint 19, however.   I tried the updated patch muffin-4.0.6-405-8a8227658bda7a582e0e2e33beaaac900653fce6.tar.gz, and the results are the same as the previous patch:  The Steam glitch persists in the top/left, but flickering/disappearing windows do not occur.  

I'm not sure why, but Cinnamon seems to think the window has lost focus when the mouse moves between the Steam sections (Store/Library/Community/etc..), and this is reflected both in the shadow of the Steam window (flickering - you can see this in the video), but also on the task bar icon for Steam.  It seems that the drawing error occurs at the top/left of the screen during the transition from out of focus to in focus.  I'm not sure why it loses focus in the first place (maybe similar issue to #414 ?), but the rendering glitch may be a timing issue between the menu/button/window being seen as in focus, and the Steam app positioning and drawing the drop-down menu (just a guess). It's like the window manager is trying to draw the shadow before the menu is fully rendered and positioned on the screen.

**Comment by jaszhix** [comment] 2019-01-18 11:21
It looks like muffin is forcing shadows on Steam. I'm not sure if that's desired behavior on our part, but I think @mtwebster might know more.

**Comment by clefebvre** [comment] 2019-02-11 15:56
Hi, https://github.com/linuxmint/muffin/files/2771746/mint191_menu_glitch.mp4.zip is happening with marco and metacity also. I don't think it's an issue with muffin, I think it's an issue with Steam using full window widgets for its menus (which results in the main window being defocused when hovering menus).

**Closed** 2019-02-16 15:12 UTC
