### ISSUE TITLE
segfault in libmuffin-clutter-0.so

### ISSUE THREAD

**Issue by sanawu** [linuxmint/muffin#571] opened 2020-10-04 18:50 UTC
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)
muffin 4.6.3

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20

 * Graphics hardware *and* driver used
driver: nvidia v: 390.138 

 * 32 or 64 bit
64 bit

Low Latency kernel

 ```

**Issue**
cinnamon[2455]: segfault at 55ac9f766ff8 ip 00007f584945e855 sp 00007ffcacfe3ec0 error 6 in libmuffin-clutter-0.so[7f58493ca000+c6000]   

**Steps to reproduce**
Open applet for "Windows Quick List" menu from the panel (location at the top)
Menu drops down
Delay in window icons appearing
Leave menu open for a few seconds after icons appear
Click the applet icon again with the menu open

**Expected behaviour**
No crash

**Actual behaviour**
cinnamon[2455]: segfault at 55ac9f766ff8 ip 00007f584945e855 sp 00007ffcacfe3ec0 error 6 in libmuffin-clutter-0.so[7f58493ca000+c6000]

**Comment by icarter09** [comment] 2020-10-07 02:26
Muffin 4.6.3
Mint 20 64bit

Followed the steps provided and was not able to reproduce the issue.

**Comment by sanawu** [comment] 2020-10-07 07:48
> Muffin 4.6.3
> Mint 20 64bit
> 
> Followed the steps provided and was not able to reproduce the issue.

Ensure there's windows open so the menu has a list

**Comment by icarter09** [comment] 2020-10-09 02:51
Menu has a list and was not able to reproduce issue.

**Comment by sanawu** [comment] 2020-10-09 07:31
> Menu has a list and was not able to reproduce issue.

VM or real install?

**Comment by icarter09** [comment] 2020-10-09 14:13
Real install. Could you provide a video of the issue? Thanks.

**Comment by sanawu** [comment] 2020-10-09 16:36
> Real install. Could you provide a video of the issue? Thanks.

I get a fallback dialog after expanding the menu and then clicking the panel icon again (you can try clicking it multiple times maybe) then segfault in the logs

**Comment by icarter09** [comment] 2020-10-10 03:46
Thanks. I'll keep checking/trying to see if I can get this issue to reproduce for me.

**Comment by clefebvre** [comment] 2020-11-09 15:23
@icarter09 you can close this if you don't have a stack trace and are unable to reproduce it.

**Closed** 2020-11-09 15:27 UTC
