### ISSUE TITLE
Drag'n'Drop between two snapped windows does not work in Nemo 5.4.3

### ISSUE THREAD

**Issue by GuidoBartoli** [linuxmint/muffin#659] opened 2022-08-15 09:23 UTC
```
 * Nemo 5.4.3 version 
 * Issue with desktop and windowed Nemo

             ...-:::::-...                 guido@SATURN 
          .-MMMMMMMMMMMMMMM-.              ------------ 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: Intense-PC2 (IPC2) 1.x 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 5.15.0-46-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 2 hours, 26 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 2147 (dpkg) 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: bash 5.1.16 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 1920x1200 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Cinnamon 5.4.10 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Mutter 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Mint-Y-Dark [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y-Dark [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: gnome-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       CPU: Intel i7-4600U (4) @ 3.300GHz 
       '.-MMMM``--:::::--``MMMM-.'         GPU: Intel Haswell-ULT 
            '-MMMMMMMMMMMMM-'              Memory: 3734MiB / 7619MiB 
               ``-:::::-``

 ```

**Issue**

Using drag'n'drop to move or copy items from one window to another does not work, even using CTRL or SHIFT keys to force copy or move respectively.

**Steps to reproduce**

1. Open two Nemo windows of two different folders
2. Drag and drop one item from the first to the second window

**Expected behaviour**

The item should be copied or moved as it should (Linux Mint 20.3 did not have this issue).

**Other information**

I attached a screencast of this behavior on my PC.
https://user-images.githubusercontent.com/16103676/184610644-24604e5f-31fa-466a-b84f-497c674fcbd3.mp4

**Comment by GuidoBartoli** [comment] 2023-01-30 10:22
I would like to add that this behavior also occurs when the window is snapped to the right side of the screen and you try to drag'n'drop an item into the folders in the left sidebar, Nemo refuses to accept both copy and move actions.

As soon as you snap the window to the left side of the screen, the problem disappears and the item is correctly moved across folders to and from the sidebar, see the screen recording below (please ignore the visual glitch caused by GPU driver fllipping interfering with the screen recorder).

https://user-images.githubusercontent.com/16103676/215450750-6d5a5415-4d8f-4f9d-b307-4138be18f0a1.mp4

**Comment by zpangwin** [comment] 2023-04-03 05:14
On Fedora 37, Cinnamon spin and wanted to confirm that this is present in Nemo 5.6.2 there as well.

Nemo is hands-down my favorite file manager and I've been using it for well over a decade at this point. Figured I'd try to do a little testing on my end and here's what I've found so far. Hopefully, it's helpful rather than just more "debugging noise" ...

1. As described in the original post and best documented with [mtwebster's comment on Nov 7, 2022](https://github.com/linuxmint/muffin/issues/659#issuecomment-1384324016), the issue occurs with left-window-to-right-window drag-and-drop but right-to-left drag-and-drop does not appear to be impacted. Dragging to bookmarks of the right-tiled window has the same issue. However, *only* drags **TO** right-tiled windows (as opposed to top/bottom/{upper,lower}-{right,left}-corner tiled windows) seem to be impacted. As long as the drag source is *from* a non-right-tiled window (e.g. left-tiled, top-tiled, etc), then same-window dragging, dragging to bookmarked folders within that window, dragging to other non-right-tiled windows, and/or dragging to desktop wallpaper are NOT impacted.
2. Interestingly, if you encounter the problem while dragging *TO* a right-tiled window and then change its tiling position and then change it *back* to a right-tiled window (e.g. `Super+Up arrow` to tile it to upper-right-corner followed by `Super+Down arrow` to undo the upper-corner tiling change), seems to fix things and the dnd operation will then work (as least it did in my testing).
3. As noted by [stitheridge on Sep 26, 2022](https://github.com/linuxmint/muffin/issues/659#issuecomment-1384323947), this seems to *also* impact drag-n-drop within the same window, if the window is tiled to the right. This seems to apply both when dragging to bookmarked folders (as in GuidoBartoli's comment/video immediately above this one), as well as other folders in the main view area/pane of the right-tiled window. But does NOT apply for right-to-left-window drags (or right-to-any other position besides right, including right-to-desktop wallpaper).
4. I have Cinnamon desktop on several computers and VMs as well as several more at my parents' place and am in a position to easily observe differences in how Nemo behaves on different setups. My primary two computers are an (older) gaming box with a single display hooked up to a tv as well as an (also older) dev box with 2 normal computer monitors. I have noticed that I am able to recreate the issue on the gaming box with no effort whatsoever, even without following mtwebster's steps, by simply opening another Nemo window and right-tiling it then trying to dnd within the same window. On my dev box, I am not able to recreate unless I follow mtwebster's steps OR I first disable my 2nd monitor in display settings. 
5. My gaming box has an older Nvidia GTX-970 card, while the dev box has an ancient AMD R9 290X... both are using proprietary drivers/codecs (nvidia drivers, mesa+codecs from rpmfusion). So I don't think AMD vs Nvidia matters.. or if it does, then other factors might need to be present as well (e.g. due to me being on Fedora, not using FOSS-only drivers, having older gpu's, etc).
6. On the gaming box with a right-tiled window doing same-window-dnd, I am able to still able recreate the issue after switching view types and for all View types (Icon/List/Compact).
7. I had fractional scaling on for both boxes. For the fractional scaling part of the equation, turning the setting off without logging out/rebooting doesn't seem to make any difference. TODO: I need to retest with a log off/reboot later when I don't have so much crap running in the background to see if that makes any difference.
8. In List View when you are dragging a file/folder over another folder as a (potential) drop-target, normally if the target folder has any contents, Nemo will expand it to show sub-folders etc. This behavior does NOT trigger when the drag operation originates from a right-tiled window.\* 
9. Using a new VM of Fedora 37 Cinnamon, in virt-manager, (offline install using Nemo 5.4.3 - *not* updated to latest in order to attempt to be as close as possible to when the issue first presented) with default (for Fedora) Nemo settings, I initially had trouble recreating the issue with left-to-right tiled dnd. After opening and closing Nemo windows several times, I closed all of the Nemo windows and opened 1 right-tiled window, then tried the same-window drag and was able to recreate the issue. After this, I was also able to recreate the left-to-right drag issue as well. The `Enable fractional scaling controls` option was ON out-of-the-box. I toggled it off and rebooted the VM, and noticed more oddities. I was able to easily recreate the right-tiled same-window issue any time I closed all Nemo instances and opened a fresh one from any `.desktop` launcher (menu, pinned panel icon, or one on desktop). Same with the left-to-right issue, if both instances were opened from launchers. **BUT** if I opened one window from a launcher, and another from the `Open New Window` context menu option, then I was not able to recreate *either* issue. Switching back to Fractional Scaling and rebooting, I observed the same behavior in the VM. I was NOT able to reproduce the launcer-related aspect of this on my bare-metal systems though. >!Also: I mean no slight to Mint or anything by testing on Fedora; they're both top-tier distros IMO... I just already had a F36 Cinnamon VM and I was able to install/test the F37 one while waiting on the Mint 21.1 iso to download!<
10. Using an existing VM of Fedora 36 Cinnamon, also in virt-manager, (up-to-date install using Nemo 5.2.4 - updated to latest in order to attempt to be as close as possible to when the issue first presented) with mostly default (for Fedora) Nemo settings - this was an existing VM install and I think I had only changed the View settings to List mode. On this one, I tried several times opening and closing Nemo, tiling back and forth but ultimately was NOT able to recreate either the left-to-right tiled drag issue OR the right-tiled same-window drag issue.
11. I was NOT able to recreate the issue with the Mint 21.1 Cinnamon live disc (Nemo v5.6.1) in a VM. Probably could have updated in-place but I didn't think of it before starting the install.
12. After installing Mint 21.1 into a VM and updating packages, after rebooting, confirmed Nemo as v5.6.4. First try (right-tiled window launched from panel/quicklaunch) seemed to work ok for dnd within the same window. Closed window. Opened two fresh Nemo windows by clicking panel icon twice quickly. Tiled one to the left, then one to the right. Made new folder on left, then tried dragging to background area on right -> did nothing when released (e.g. issue present / dnd did not work). Dragging left-to-right onto a folder, same thing (dnd did not work). Right-window: created two folders and tried to drag one into the other -> same thing (dnd did not work).



\* Probably not the best place for this and sorry about that but as a side-question / just in case anyone happens to know... I've actually been interested for a while now in writing a patch to make the folder dragndrop/expansion behavior configurable as a setting (and possibly some other stuff too). Just curious where the best place to ask dev questions and such *specifically related to Nemo* would be? (e.g. if I had build questions / didn't understand something in the code / wanted to gauge likelihood of an idea being accepted or rejected before I started working on something / etc)

**Comment by zpangwin** [comment] 2023-04-30 14:29
Moved to Fedora Cinnamon 38 (Nemo 5.6.4) last week and just wanted to confirm that above also applies there as well.

Also noticing that on my PC that is connected via HDMI to a TV (with no other monitors and using default display settings), that the cursor does not stop at the right-edge of the screen but it does stop at the left/top/bottom edges. I have been using this setup for years with both Mint and earlier versions of Fedora and have long since disabled [overscan](https://www.technewstoday.com/display-cut-off/) on the tv; nothing is cut-off visually and as noted it is only affecting the right-edge of the screen. Mentioning it only as I am not sure if this could potentially be related but given that it seems to have the same left/top/bottom ok but right has issue characteristics, I thought it it being related was at least somewhat plausible.

One thing I do notice that is weird is on Display Settings > Layout, I see my LG TV is "monitor 2" and I have "Unknown Display" as monitor 1, despite not having any other physical monitor attached nor even any other HDMI / displayport / VGA / DVI cables connected. The "Unknown Display" has the toggle to the right grayed out, which on real monitor would mean it is disabled. My "LG TV" monitor is both enabled and is marked as the primary monitor

![2023-04-30_100339 png](https://user-images.githubusercontent.com/29719631/235358463-2f9e7f2b-668e-49ae-9548-8af457d3a7aa.png)

![2023-04-30_100357 png](https://user-images.githubusercontent.com/29719631/235358513-b47c5983-21cb-49da-834f-aff19a4b5090.png)

**Comment by trr** [comment] 2023-06-19 03:36
I can reproduce this with a nemo window snapped to the right half of the screen only and no other nemo window open at the time, just dragging and dropping a file from that window into another part of that same window (ie, a visible subfolder) does not work.

Un-snap the window from the right half of the screen and drag-and-drop within the window works.

**Comment by NintendoManiac64** [comment] 2023-07-31 22:42
I believe I have pretty much narrowed-down how to cause this issue and how to undo the issue in an extremely repeatable and/or reproducible manner. And, yes, it still occurs in Mint 21.2.

(not so?) fun fact: the issue even occurs dragging & dropping within a single nemo window, not just from one to another

**TO CAUSE**
Simply dock the nemo window on the left or right half of your screen, close nemo, open nemo again, and dock it on the right side of your screen.

Now anything being dragged into that nemo window docked on the right side will not be placed where it's supposed to go.


**TO UNDO**
Simply manually resize the nemo window docked on the right side or maximize its window, close it, re-open it, and then dock it again onto the right side.

As long as you don't close that nemo window *again* and immediately dock it onto the right side, you should be able to drag & drop files/folders without issue even while it's docked.

**Video demonstration (live Mint 21.2)** 
[video.webm](https://github.com/linuxmint/muffin/assets/11896003/b4308044-57ba-4899-8d92-de4a5415da9c)

**Comment by 6630507** [comment] 2023-09-19 03:26
What I find so maddening about the issue is that it violates the logic
of rsync syntax: source --> destination

The source is on the left and the destination on the right.  But this
bug prohibits that, while allowing drag-and-drop trnsfers right-to-
left.  It's sacriligious.  

It also violates the logic of the cp command, which is also left -->
right.

This Nemo bug violates the logic of Linux somehow.

**Comment by NintendoManiac64** [comment] 2023-09-19 05:49
> What I find so maddening about the issue is that it violates the logic of rsync syntax: source --> destination

>The source is on the left and the destination on the right.

If you look at my video, you'll see that the issue doesn't really have much to do with left --to-> right and is instead related to how pinning a window in the right side makes it "bug out" regardless of where the source location is, including a source within the very same window.

**Comment by IfGremlinThen** [comment] 2023-09-27 21:39
Posting my two cents because this is _by far_ the biggest bug impacting my workflow right now.

This occurs in **Linux Mint 21.2** & **Linux Mint: Debian Edition 6** (the latest versions of both operating systems).\
I did not experience this issue in Linux Mint 20.3.

I am using Cinnamon 5.8.4, Muffin 5.8.1, & Nemo 5.8.5 in both operating systems and this occurs both on my AMD Ryzen 3 desktop computer and ASUS laptop.

The main thing that I haven't seen mentioned yet (do correct me if I've missed it) is that drag-and-drop DOES move the files sometimes, but it's as though the drop point on the screen is _offset_ by some amount, so sometimes I'll move files from the desktop to a folder, and the files will disappear, but they won't appear in the destination folder.  I haven't tested it yet, but I believe that the file selection is depositing at a point offset to the left of the actual cursor by some distance and that is dropping the selection into some of the My Computer/Bookmarks shortcuts in the left panel of Nemo's file explorer.

**_I believe..._** that when a file is dragged into a right-tiled Nemo window, the actual drop point is offset to the _left_ by some unknown pixel distance.  Obviously there are some parts of the Nemo file manager's windows that are not legitimate targets for moving files, so the effect of moving a selection to a window offset to these points is to treat it as though the file wasn't moved at all, because the destination is invalid.  However, sometimes the offset is over an another directory, or shortcut to a directory, which are valid destinations, and the files will be moved there, in which case the apparent effect is that the files you moved have simply disappeared (though you can Ctrl+Z to get them back).

Hopefully this helps.  If this isn't a dead issue I'll certainly test my theory.

**Comment by NintendoManiac64** [comment] 2023-09-28 00:56
>  I haven't tested it yet, but I believe that the file selection is depositing at a point offset to the left of the actual cursor by some distance and that is dropping the selection into some of the My Computer/Bookmarks shortcuts in the left panel of Nemo's file explorer.

You can see this in [my above-posted video](https://github.com/linuxmint/muffin/issues/659#issuecomment-1659288808) at around the 50 second mark.

**Comment by 6630507** [comment] 2023-09-28 02:01
>this is by far the biggest bug impacting my workflow right now


This is a daily nuisance for me too.

It's not always, but part of the circumstance might be unrelated to the
bug, and might be a subtle behavioral thing.

For example, if your drag from left to right and it doesn't work,
super-up or super-down the window to tile it into a corner, and then
back into the whole right side, it works.

But, yeah, its a weird bug, and it violates the source-
destination/left-right logic of many Linux text commands

**Comment by NintendoManiac64** [comment] 2023-09-28 02:10
> it violates the source- destination/left-right logic of many Linux text commands

As I already stated, I really don't think this has anything to do with left-to-right not working and has everything to do with a window docked on the right side of your screen being borked since this issue can even occur within a single window docked on the right side of the screen with files dragged downwards from the top of the window.

I'm starting to feel like a bit of a broken record with pointing out the [video demonstration I made](https://github.com/linuxmint/muffin/issues/659#issuecomment-1659288808) that, as far as I can tell, exactly identifies the problematic behavior in question in an extremely repeatable manner.

**Comment by 6630507** [comment] 2023-09-28 13:52
I understand the underlying technical issue is more nuanced that simply
left-to-right movements, but that's how I experience the bug in my
workflow.

**Comment by IfGremlinThen** [comment] 2024-03-09 19:23
Bump because this is **still** my biggest issue with Linux Mint at the moment.  The last two versions of Mint have released with this bug and it _really_ should have been squashed by the 6.0 release of Cinnamon.

I can now confirm this bug is still present as of LM 21.3, LMDE 6, w/ Cinnamon 6.0.4, Muffin 6.0.1, & Nemo 6.0.2.


Everything I've mentioned before about the cursor effect being offset has been borne out many times through daily usage.  I was able to demonstrate it again while typing this:

https://github.com/linuxmint/muffin/assets/81646252/bb5c910d-9792-4c11-813c-e226e6ffb54b

**Closed** 2024-10-24 16:13 UTC
